algoritmo "A Área de um retângulo"
// Função :
// Autor : Ednaldo
// Data : 08/12/2025
// Seção de Declarações 

var
   largura, comprimento, area: real
inicio
   escreva("Digite a largura do terreno: ")
   leia(largura)

   escreva("Digite o comprimento do terreno: ")
   leia(comprimento)

   area <- largura * comprimento

   escreval("A área do retângulo é: ", area)
fimalgoritmo


