algoritmo "Perimetro de um quadrado"
// Função :
// Autor :   Ednaldo
// Data : 29/11/2025
// Seção de Declarações 
var
  lado, perimetro: Real
  
inicio
// Seção de Comandos 
   escreval("Calcule o perimetro do quadrado")
   escreval()
   escreva("Digite o comprimento do lado do quadrado ( em cm.")
   leia(lado)
   perimetro <- lado * 4
   escreval()
   escreval("O perimetro do quadrado", lado, "é:", perimetro, "cm.")
   
   
fimalgoritmo
