algoritmo "Salário com adicional"
// Função :
// Autor :  Ednaldo
// Data : 08/12/2025
// Seção de Declarações 
   var
   salario_base, adicional, salario_total: real
inicio
   escreva("Digite o salário base: ")
   leia(salario_base)

   escreva("Digite o valor do adicional: ")
   leia(adicional)

   salario_total <- salario_base + adicional

   escreval("O salário total é: R$ ", salario_total)
fimalgoritmo
