algoritmo "Temperatura positiva"
// Função :
// Autor :  Ednaldo
// Data : 09/12/2025
// Seção de Declarações 
var
   temperatura: Real
inicio
// Seção de Comandos 
   escreva("Digite a temperatura registrada: ")
   leia(temperatura)
   
   se (temperatura >= 0) entao
      escreval("A temperatura é positiva.")
      
   senao
   
      escreval("A temperatura não é positiva.")
      
   fimse
fimalgoritmo
