algoritmo "Verificação de Múltiplos"
// Função :
// Autor : Ednaldo
// Data : 09/12/2025
// Seção de Declarações 
var
   numero: Inteiro
inicio
// Seção de Comandos 
   escreva("Digite o número da peça: ")
   leia(numero)

   se (numero % 3 = 0) entao
      escreval("O número é múltiplo de 3. Revisão necessária.")
   senao
      escreval("O número não é múltiplo de 3. Revisão não necessária.")
   fimse
fimalgoritmo
